version: "3"
services:
  app:
    restart: always
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5532/postgres
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:latest
    ports:
      - "5532:5532"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres